-- 중성화 수술한 동물 정보 서칭
-- 보호 시작할 땐 중성화 X, 입양 시에는 중성화 O인 동물 -> INNER JOIN
-- ANIMAL_ID, ANIMAL_TYPE, NAME를
-- ANIMAL_ID 순으로 조회(ASC)
SELECT INS.ANIMAL_ID
    , INS.ANIMAL_TYPE
    , INS.NAME
FROM ANIMAL_INS INS
    , ANIMAL_OUTS OUTS
WHERE INS.ANIMAL_ID = OUTS.ANIMAL_ID
AND SUBSTR(INS.SEX_UPON_INTAKE, 1, 1) = 'I'
AND SUBSTR(OUTS.SEX_UPON_OUTCOME, 1, 1) IN ('S', 'N')
ORDER BY ANIMAL_ID ASC;