-- 데이터가 유실 
-- OUTS.DATETIME은 있는데 INS.DATETIME이 없는 것을 찾아라.
-- 어떤 것을?
-- ANIMAL_ID와 NAME을
-- 어떻게?
-- ID 순으로
SELECT OUTS.ANIMAL_ID
    , OUTS.NAME
FROM ANIMAL_INS INS, ANIMAL_OUTS OUTS
WHERE INS.ANIMAL_ID(+) = OUTS.ANIMAL_ID
AND INS.DATETIME IS NULL
ORDER BY ANIMAL_ID;