-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') -- DATEFORMAT은 필수인듯
FROM MEMBER_PROFILE
WHERE MONTH(DATE_OF_BIRTH) = 3 && TLNO IS NOT NULL && GENDER = 'W'
ORDER BY MEMBER_ID;