-- INS
-- OUTS
-- 일부 동물의 입양일이 오기입된상태
-- INS.DATETIME > OUTS.DATETIME ANIMAL_ID와 NAME을 조회
-- 정렬: 보호 시작일이 빠른 순(오름차순)
SELECT INS.ANIMAL_ID, INS.NAME
FROM ANIMAL_INS INS, ANIMAL_OUTS OUTS
WHERE INS.ANIMAL_ID = OUTS.ANIMAL_ID
AND INS.DATETIME > OUTS.DATETIME
ORDER BY INS.DATETIME ASC;